### ISSUE TITLE
Import new Test Cases

### ISSUE THREAD

**Issue by mattr52** [ALM-Rangers/Offline-Test-Execution-Extension#17]
I understand this can be used to export test cases to Excel, do the tests off-line, and then import the results back into MTM. I'm wondering if it will also do a slight variation on that. I currently have many  test cases written up in Excel and would like to get them all imported into MTM.  Will this extension do that for me?

**Comment by mattias-skold** [comment]
Straight and honest answer 
- Sadly, No. 

There is however an excel copy&paste import built into the product. Please refer to this blogpost https://blogs.msdn.microsoft.com/tfssetup/2015/03/27/migrating-test-cases-in-tfs-2013/ 
Technically, there is a huge difference between importing test results to a pre-defined test plan, and trying to creating a test plan with everything attached from nothing. From an information perspective, there is also quite an amount of information missing to support creating test cases during the import. 
It would also be much simpler to build a dedicated solution that only supports importing test cases.
