### ISSUE TITLE
Export always creates empty / blank xlsx file

### ISSUE THREAD

**Issue by caltseng** [ALM-Rangers/Offline-Test-Execution-Extension#18]
It works for one of the projects that I'm in, but doesn't work for the one that I'm tried to export. 

Are there known limitations in feature functionality that would prevent export? I don't get any error messages when attempting to export.

**Comment by mattias-skold** [comment]
No - no known limitations, If you can press F12 in the browser, rerun the export and share the output from the console window I can take a look.

**Comment by caltseng** [comment]
[olsapps.visualstudio.com-1550095987724.log](https://github.com/ALM-Rangers/Offline-Test-Execution-Extension/files/2862425/olsapps.visualstudio.com-1550095987724.log)

@mattias-skold  - Attached are the logs for a small test suite of 4 that I'm testing with. I've tested with other suites and they all fail. The network is 200's all across the board.

**Comment by mattias-skold** [comment]
Looks clean, how big is the generated file ? Can you share it (or send it by email if you dont want to post it)

**Comment by caltseng** [comment]
Thank you @mattias-skold  for debugging the issue with me. We found that the test plan name was too long. After renaming the test plan name to a shorter "Test Plan", the export worked magically as expected.
