### ISSUE TITLE
import error :No valid test point to import found,why?

### ISSUE THREAD

**Issue by zhangwk02** [ALM-Rangers/Offline-Test-Execution-Extension#20]
![image](https://user-images.githubusercontent.com/38233062/55221637-e4b79100-5244-11e9-9614-53e462e7770f.png)

**Comment by mattias-skold** [comment]
Are you made any changes to the test plan after the file was exported ? 
Could you share the file you try to import by sending it to extension-support@mskold.com

**Comment by zhangwk02** [comment]
I deleted the TestCaseId and TestPointId 。I have sended the file to you 
@mattias-skold
