### ISSUE TITLE
Azure DevOps Test Plan: Offline-Test-Execution-extension can not import successfully

### ISSUE THREAD

**Issue by maping** [ALM-Rangers/Offline-Test-Execution-Extension#21]
Step to reproduce the issue:

1. I install the Offline-Test-Execution-extension.

2. set up some tests manually.

3. export that test cases to an excel file.

4. try to import the exported test cases in another project, failed, message is

(1) Can /'t find test plan id 47

(2) No valid test point to import found

Env: Chrome browser 72.0.3626.121 and MS excel 16.24

**Comment by mattias-skold** [comment]
You can only import test results back to the project you exported them from...

**Comment by maping** [comment]
@mattias-skold , thank for reply.
the purpose that I want to export test cases first is to get a correct excel.
Can you tell me how to create a excel that can be imported successfully?

**Comment by mattias-skold** [comment]
As above, you can only import results back to the testplan (and test points) you exported them from. 
To create an excel that can be imported - select the test plan you want to import the results to, and export it to excel using the extension
