### ISSUE TITLE
Import Test Results Fails

### ISSUE THREAD

**Issue by MaxMan79** [ALM-Rangers/Offline-Test-Execution-Extension#23]
I am simply trying to test the export/import feature.  I did the following...

1. Exported a Test Suite to an xlsx file
2. Opened the file in Excel 2016
3. Changed all test step outcomes to "Passed"
4. Saved the file
5. Dragged the xlsx file to the Import Upload section of the same Test Suite (Validation passed, see image below)
![Validated](https://drive.google.com/uc?export=view&id=1-H7W_A_U-EIYZSWsJvMOAfv2G-mtmZoR)
6. Clicked Import (Received a "Failed" error, see image below)
![Failed](https://drive.google.com/uc?export=view&id=1HECQNVQcTNM5URI4zsWn7yRGhvt22Ib_)

This is running on Team Foundation Server 2017 Update 3.1 (version 15.117.27414.0).  Here's a link to the actual [spreadsheet](https://drive.google.com/file/d/1SSuYT-_MDR1xBchiS9M9wAEq1Q8j6VSL/view?usp=sharing), if needed.  Any help would be much appreciated!

**Comment by mattias-skold** [comment]
Can you 
Press F12 in the browser to activate the browser debug tools
Switch back to TFS and do the import again
Switch back to the debug tools, copy the content of the console window and share with me. You can email it on extension-support@mskold.com
