### ISSUE TITLE
Azure Devops service can't export to excel 

### ISSUE THREAD

**Issue by zhangwk02** [ALM-Rangers/Offline-Test-Execution-Extension#25]
{"count":1,"value":{"Message":"The requested resource does not support http method 'GET'."}}

![image](https://user-images.githubusercontent.com/38233062/57352802-12bfb780-7199-11e9-9c6b-9c387a3ec4d5.png)

**Comment by mattias-skold** [comment]
Can you provide more context ? What is not working in OTE ? 
The provided screenshot doesnt give any clue on what could be potential the issue. (The failed request to /Example/HalloDevOps something is probably made from another extension or even Microsoft code, unless your organization/Project is Example/HalloDevOps. 

The second failed request is made by Microsoft to its internal telemetry for loading the extension, it failing has (should have) no impact on the execution of OTE extension.

**Comment by zhangwk02** [comment]
can u speak chinases

**Comment by zhangwk02** [comment]
本地化部署Azure Devops后，安装OTE这个插件，然后到处用例，导出来的用例没有内容，只有标题。F12查看浏览器请求信息，结果报错。can you speak english @mattias-skold

**Comment by mattias-skold** [comment]
@zhangwk02 Sorry to say, Im limited to English

**Comment by zhangwk02** [comment]
@mattias-skold  After localizing Azure Devops, install the OTE plugin, and then use the use case everywhere. The exported use case has no content, only the title. F12 checks the browser request information and the result is incorrect. Can you speak english @mattias-skold
