### ISSUE TITLE
Import of Offline test - Comments not imported

### ISSUE THREAD

**Issue by JonnyArsta** [ALM-Rangers/Offline-Test-Execution-Extension#27]
Hi,
We are preparing for a UAT with the Offline Test Execution extension but we run in to an issue.

I export a test case (I’ve attached it) and fill it out with “Outcome” (Dropdown) and Comment (Text)
When I then import it back in to Azure DevOps (attached a screenshot of the import dialogue), the comments field are left out. If I run them Online in Azure Devops the comments are visible.
I’ve tried different ways. With and without national characters, with and without double quotes around the comment. I’ve done testing on test cases with parameters (like the one attached) and also with just one test step and no fuzz in it what so ever. Same results, no comments.

This is a show stopper for us since we need feedback in form of comments if a UAT user is reporting a failed test step.

Is this a known bug or if not, can you reproduce it with my XLSX file and/or with one of your own files?

Please advise on how I can move forward with this.

[OTE_Suite for Import_-- All --_-- All --.xlsx](https://github.com/ALM-Rangers/Offline-Test-Execution-Extension/files/3319648/OTE_Suite.for.Import_--.All.--_--.All.--.xlsx)
![Screen shoot of Import](https://user-images.githubusercontent.com/51951777/59999151-94907500-9661-11e9-8a5e-c2635206d636.jpg)

**Comment by mattias-skold** [comment]
Hi Jonny 
I tried to repro it on VSTS/Azure DevOps but it seems to be working .. 
Can you please drop en email to extension-support@mskold.com 
 and if possible include info on your environment, extension version,  and perhaps a console log from running the import
