### ISSUE TITLE
Extension point not available in New Test Plans Page

### ISSUE THREAD

**Issue by wpschaub** [ALM-Rangers/Offline-Test-Execution-Extension#30]
When users enable the **New Test Plans Page** feature, the **Offline test execution** vanishes.

**Old Test Suite View**
![image](https://user-images.githubusercontent.com/12176555/65905596-b2165e80-e375-11e9-9786-8c0788972d05.png)

**New Test Suite View**
![image](https://user-images.githubusercontent.com/12176555/65905675-df630c80-e375-11e9-96dc-23c01a79d75e.png)

**Comment by mattias-skold** [comment]
The new Test hub is in preview and is not feature complete yet. One of the things still not implemented is support for extensibility. I have checked with Microsoft and they intend to implement the same extensibility for the new test plans hub as they have in the current hub. 
That means that as soon as Microsoft implements support for extensions in the new Test Hub, the Offline test execution extension will light up.

**Comment by georjino** [comment]
We are running the same problem, meanwhile can you suggest any alternative?
Is there any time frame for that?

**Comment by mattias-skold** [comment]
The work around is to turn of the Preview for new Test Hub (and return to the production version) 
If you do so -please State lack of extensibility /My favorit extension doesnt work as reason.

For the timeline of Microsofts development of the new test hub, this is the official post https://docs.microsoft.com/en-us/azure/devops/test/new-test-plans-page?view=azure-devops#journey For further questions on Microsofts plans - please contact Microsoft

**Comment by georjino** [comment]
Well noted, thank you so much for your prompt action
