### ISSUE TITLE
Add-On not working with latest DevOps update

### ISSUE THREAD

**Issue by fgudelj** [ALM-Rangers/Offline-Test-Execution-Extension#31]
With the latest DevOps update, extension is not appearing anymore:

![image](https://user-images.githubusercontent.com/57663525/68770198-04f65d80-0626-11ea-9b18-c8687866f79c.png)

**Comment by mattias-skold** [comment]
The new Test hub is in preview and is not feature complete yet. One of the things still not implemented is support for extensibility. I have checked with Microsoft and they intend to implement the same extensibility for the new test plans hub as they have in the current hub.
That means that as soon as Microsoft implements support for extensions in the new Test Hub, the Offline test execution extension will light up.
