### ISSUE TITLE
Export functionality in “Offline Test Execution” utility is not pushing outcome and comments data in external excel files

### ISSUE THREAD

**Issue by GopalRamappa-QA** [ALM-Rangers/Offline-Test-Execution-Extension#33]
Environment:
Brower: Internet Explorer 11
TFS: 2018 (Web Version)

Steps to Reproduce:
a. Execute few manual test cases , set the status and comments - Save the changes
b. Now export the test plan using “Offline Test Execution” utility
c. Once the export completed check the excel file generated
d. Check the columns “Comments” and “Outcome”

Expected Result: “What you see is what you get”. The data which is populated at each test case level should be exported successfully (including Outcome and Comments data)

Actual Result: Exported data is partial and Outcome and Comments data is not populated in the exported spreadsheet.

Repeatable: Yes

**Comment by mattias-skold** [comment]
The purpose of the Offline Test Execution is to allow offline execution of est and not to be a general export tool.

**Comment by GopalRamappa-QA** [comment]
Outcome and Comments are vital segments in any test case execution.. I feel without these two details import and export operations looks incomplete.
Please have a look into this and try to include at least thee 2 columns in Import and Export utilities. I am sure this will definitely add more value during test execution also helps in audit process

**Comment by GopalRamappa-QA** [comment]
> Environment:
> Brower: Internet Explorer 11
> TFS: 2018 (Web Version)
> 
> Steps to Reproduce:
> a. Execute few manual test cases , set the status and comments - Save the changes
> b. Now export the test plan using “Offline Test Execution” utility
> c. Once the export completed check the excel file generated
> d. Check the columns “Comments” and “Outcome”
> 
> Expected Result: “What you see is what you get”. The data which is populated at each test case level should be exported successfully (including Outcome and Comments data)
> 
> Actual Result: Exported data is partial and Outcome and Comments data is not populated in the exported spreadsheet.
> 
> Repeatable: Yes

Recent Updates:
Outcome and Comments are vital segments in any test case execution.. I feel without these two details import and export operations looks incomplete.
Please have a look into this and try to include at least thee 2 columns in Import and Export utilities. I am sure this will definitely add more value during test execution also helps in audit process

**Comment by mattias-skold** [comment]
As I stated earlier - It is not an import and export tool. 
Its only purpose is to allow user to execute existing test points offline and transfer the result back to the same existing test point. 

Then it comes to the potential value of having the last test result aviable then executing a test case, I have ocationally heard similar asks. But I also know that for a large number of organization that is very clear on that they DONT want that.  I strongly doubt that pre setting the previous test results as the new test results is a good idea. For those who wants current test case result as info- there is export tools availbe (for example Enhanced Export and Enhanced Export PRO) 

Its also qute technically and logical challenging to show the latt executed test results (potentially from a previous test case version) on the current version of the test case. 

All together - I think the overall value for Offline Test Execution is debatable at best, and the cost of implementation is quite high. I have no short term plans to look into this, but Im open to accept pull requests on it - if its optional to include it, and there is a good strategy for handling the revision problems.
