### ISSUE TITLE
Not Able to export to Excel- Azure DevOps Server 2019 Update 1

### ISSUE THREAD

**Issue by sriramdasbalaji** [ALM-Rangers/Offline-Test-Execution-Extension#38]
Hi,

We wanted to use this extension for offline test execution. Unfortunately, it is not working as expected in Azure DevOps Server 2019 update 1. We are not able to export to Excel. Please let me know if this can be fixed, Or do we need to enable anything to make it work.

Thanks

**Comment by mattias-skold** [comment]
Are you using Chrome , if so in what version ? 
Can you elaborate on what part is not working ? 

The latest release of chrome (>83) is blocking downloading files from azure devops extensions deployed onprem.

**Comment by sriramdasbalaji** [comment]
Hi @mattias-skold ,

Thank you very much for your prompt response. Yes, we are using Chrome version 83.0.4103. When we click on Export Button it's not downloading Excel file with Test cases. And no issue is tracked in Debug console.

Thanks

**Comment by mattias-skold** [comment]
Chrome changes (broke backward compat)  for handling of sandboxed iframes with update 83. This is documented at [https://www.chromestatus.com/feature/5706745674465280](https://www.chromestatus.com/feature/5706745674465280) 

TFS/AzureDevOps onprem uses sandboxed iframes for extensions, this is a part of your tfs installation and nothing extensions can fix. Microsoft needs to patch TFS to make it work with Chrome 83 to solve this, Please file a ticket with Micrsosoft to help them prioritize this.

As a work around - please downgrade chrome or use another browser.

**Comment by mattias-skold** [comment]
An update - Microsoft has now fixed this issue in Azure DevOps Server 2020, contact Microsoft support to request a patch for your version.
