### ISSUE TITLE
Comments on individual steps is not imported

### ISSUE THREAD

**Issue by godtesen** [ALM-Rangers/Offline-Test-Execution-Extension#41]
If you write a comment on the first line in the test case (the title line) it is imported as as comment ok. But if you fail individual steps and write comments to explain why they are failed, then this is not imported at all.

**Comment by mattias-skold** [comment]
this is a duplicate with #36 and resolved with pr #37. Were currently waiting for Microsoft to enable us to push an update to the Marketplace
