### ISSUE TITLE
Download is disallowed. The frame initiating or instantiating the download is sandboxed, but the flag ‘allow-downloads’ is not set. 

### ISSUE THREAD

**Issue by stoobles** [ALM-Rangers/Offline-Test-Execution-Extension#56]
Still getting the above error message when pressing the 'Export to Excel' button using Chrome Version 97.0.4692.71 (Official Build) (64-bit) and Edge Version 97.0.1072.62 (Official build) (64-bit)

**Comment by mattias-skold** [comment]
This is not a problem with the extension, it's a bug in your version of TFS,
Either upgrade your TFS to Azure DevOps 2020 or contact Microsoft Support to get a patch if your on a supported version. 

Please refer to issues #38, #42, #43 & #50 for more details and a technical background.
