### ISSUE TITLE
Export to excel is not working.

### ISSUE THREAD

**Issue by AMARAVATHIVSRKPRASAD** [ALM-Rangers/Offline-Test-Execution-Extension#58]
In Azure DevOps Server  TestPlans--> Offline Test Execution  Export feature is not working.
When you click on Export it suppose to export to excel(download in xls) but its not happening. No action is being performed. It is idle.

Below are the details of Azure DevOps being used.
Version: Azure DevOps Server(On-Prem) Update 1.1
Reproduce step: Connect to  Azure DevOps Project in web-->Test Plan-->Select TestPlan-->Offline Test execution-->Export
![image](https://user-images.githubusercontent.com/112699369/188127417-a2b4f575-5b4b-4113-b0df-31ed5b88c561.png)

**Comment by mattias-skold** [comment]
What is the version of Azure DevOps Server ? Update 1.1 doesn't say much as it can be either 2018, 2019, 2020 .
From your screenshot it looks like its pre 2020 - and in that case there is a compabiolity problem with Azure DevOps Server and modern browsers that blocks downloads. If you either upgrade to Azure DevOps Server 2020 or reach out to Microsoft Support you can get a patch for your Azure DevOps server.

**Comment by AMARAVATHIVSRKPRASAD** [comment]
> What is the version of Azure DevOps Server ? Update 1.1 doesn't say much as it can be either 2018, 2019, 2020 . From your screenshot it looks like its pre 2020 - and in that case there is a compabiolity problem with Azure DevOps Server and modern browsers that blocks downloads. If you either upgrade to Azure DevOps Server 2020 or reach out to Microsoft Support you can get a patch for your Azure DevOps server.

Sorry for confusion. We are using Azure DevOps Server 2019 Update 1.1.
Till two weeks before, It was working fine. It suddenly stopped working.

**Comment by mattias-skold** [comment]
Updated the browser recently ? If your runing a chronium browser later then R83 - you can not download files from extensions Azure DevOps 2019 unless you patch it.

**Comment by AMARAVATHIVSRKPRASAD** [comment]
We are using Chrome version of **105.0.5195.102** and Edge version of **103.0.1264.49**

**Comment by mattias-skold** [comment]
Then you need to either 

- Upgrade or patch Azure DevOps Server 
- Downgrade to an older browser (<83)

Chrome added a new safety feature (and broke the HTML standard) by adding a new flag for Iframes to allow downloads. IFrames that doesnt have the flag are not allowed to download files.

Microsoft Azure DevOps loads all extensions in IFrames and is now setting the new flag in Azure DevOps Server 2020. If you reach out to Microsoft support they should also be able to provide a patch for your server. 

If you press F12 in the browser and tries to download the file - you should be able to confirm this as the problem.
**This is not a defect or anything we can solve in the extension**. The only way to solve it is as above - upgrade azure devops server or switch to an older browser.
