### ISSUE TITLE
Linking errors while building the project

### ISSUE THREAD

**Issue by adithyagaurav91** [ALM-Rangers/Offline-Test-Execution-Extension#59]
I am a software developer from Canarys Automations Pvt. Ltd. We wanted to use the Offline Test Execution extension which is available in the [Marketplace](https://marketplace.visualstudio.com/items?itemName=ms-devlabs.OfflineTestExecution). We explored that and additionally, we wanted to have some more features as part of this. We planned to use the source code from your GitHub repository to extend the features to it, while in that process we encountered a lot of errors which was related to the usage of old/deprecated version libraries used in it. Can we get assistance here in resolving this issue?

**Comment by mattias-skold** [comment]
The obvious answer is - it depends :)
What is the old/deprecated libraries you have in mind ? As this extension supports on-prem server - there is also restriction on what of the new libraries we can use.  We are for example stuck with the "old" VSS SDK as Onprem support for the new Azure Devops Web SDK is lacking.

If you want to contribute into extending the feature set of the Offline Test Execution extension, we can have a collaborative effort on it. If you are just planning to build your own solution and not contribute back - there is little/no value for the community to resolve issues you may encounter. 

What type of features are you planning to add ? Could you add those as issues so we can see if its doable/fits in OTE 

Maybe @MOlausson have something to add to the conversation.

**Comment by adithyagaurav91** [comment]
Hi @mattias-skold ,
Thank you for your reply on this issue, as we were looking for the Azure DevOps Service, we tried to download the code and compile it with the latest version of packages to run it with some minor modifications on Azure DevOps Service and we came along the problems of compiling.

**Comment by mattias-skold** [comment]
Without knowing what problems you hit its hard to say anything. 

We have no plans currently to abandon onprem support and rebuild the extension with the new Azure DevOps SDK. 
If you want to contribute to the extension and find issues - please raise issues for the specific problems. 
If you are missing features - please place issues or start a PR to discuss the suggested feature. Who knows we might save you a lot of effort just discussing what's possible to do. 

If you're only looking to build your own version of the tool and not contribute back to the community, I doubt you will get much support from the community...

**Comment by MOlausson** [comment]
@adithyagaurav91 I agree with @mattias-skold that you should open an issue or submit a PR to add features to the extension. 

Cloning the open source code and republishing as another open source project doesn't make sense. 

Closing the issue, feel free to open a new issue with the concrete problem.
