### ISSUE TITLE
Vulnerability Issue Found

### ISSUE THREAD

**Issue by Soni-VL** [ALM-Rangers/Offline-Test-Execution-Extension#61]
Vulnerability issue found in the code, kindly suggest who is the responsible person to contact and report the issue.

@teilmeier , could you please suggest who is the responsible person to contact and report the vulnerability issue?

**Comment by teilmeier** [comment]
Hi @Soni-VL. thanks for bringing this up.
You can find the contributors here: https://github.com/ALM-Rangers/Offline-Test-Execution-Extension#contributors and the contact email is mktdevlabs@microsoft.com.

**Comment by danhellem** [comment]
@Soni-VL since the code is open source, you can just report the problem by creating a new issue with the details. We will then review and address as needed.

**Comment by MOlausson** [comment]
@Soni-VL you can also reach out to me as one of the maintainers of the devlabs extensions. Closing this as resolved.
