### ISSUE TITLE
OffLine Test Execution extension is not working

### ISSUE THREAD

**Issue by muthu3758** [ALM-Rangers/Offline-Test-Execution-Extension#62]
Upon clicking on Export To Excel option nothing is happening. We are using AzureDevOpsServer 2019.

**Comment by mattias-skold** [comment]
As you can read in issue #56 (and many many other duplicates) This is a problem with Chrome broke the HTML standard and disabled download from sandboxed iframes.

You have 2 paths forward :

Run an older browser (before chrome R58)
Contact Microsoft support to get an path for your onprem tfs server that compensates for the new defecto HTML standard.
