### ISSUE TITLE
How to fix error in test case data?

### ISSUE THREAD

**Issue by sampadaz** [ALM-Rangers/Offline-Test-Execution-Extension#9]
Hi,
When I am importing test execution details from excel sheet, I get error
 "Found 1 errors in test case data"
There is no way to figure out what this means. No context provided by the tool what error test case data has. Is there a way to fix this apart from doing manual analysis.

**Comment by mattias-skold** [comment]
In the grid of validated import data (below the validation summary)  - errors and validations is marked on row level, just go through the errors and warnings and you will find a more detailed error on the tooltip of the row with the error ...

**Comment by sampadaz** [comment]
@mattias-skold Thank you for this info! It helped and I could fix the issue.
